from decimal import Decimal
from typing import Protocol

from trader.exchange.models import Account, Balance, Order, SymbolInfo, Ticker
from trader.models import Candle


class ExchangeAdapter(Protocol):
    def get_account(self) -> Account: ...
    def get_balances(self) -> tuple[Balance, ...]: ...
    def get_ticker(self, symbol: str) -> Ticker: ...
    def get_klines(self, symbol: str, interval: str, limit: int = 100) -> tuple[Candle, ...]: ...
    def get_exchange_info(self, symbol: str) -> SymbolInfo: ...
    def place_order(
        self, symbol: str, side: str, quantity: Decimal, client_order_id: str
    ) -> Order: ...
    def get_order(self, symbol: str, client_order_id: str) -> Order: ...
    def cancel_order(self, symbol: str, client_order_id: str) -> Order: ...
    def get_open_orders(self, symbol: str) -> tuple[Order, ...]: ...
